name = "GenericDecMats"
uuid = "a98d1166-8d3f-4eaf-b2a4-26e52ad22d9c"
authors = ["ThomasBreuer <sam@math.rwth-aachen.de>"]
version = "0.1.1"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
JSON = "0.21"
Requires = "1.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
